# Generated by Django 2.0.6 on 2020-04-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(max_length=20)),
                ('brief', models.TextField(blank=True, null=True)),
                ('broadcast', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=20)),
                ('cover', models.ImageField(upload_to='pics')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('pic', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.FileField(blank=True, null=True, upload_to='mp3')),
                ('size', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('album_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('address_item', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.CharField(blank=True, max_length=20, null=True)),
                ('regist_time', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
