# Generated by Django 2.0.6 on 2020-04-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='duration',
            new_name='time_long',
        ),
        migrations.AddField(
            model_name='chapter',
            name='audio',
            field=models.ImageField(null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='create_date',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
