# Generated by Django 2.0.6 on 2020-04-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
    ]
