# Generated by Django 2.0.6 on 2020-04-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
