# Generated by Django 2.0.6 on 2020-04-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(max_length=20)),
                ('brief', models.TextField(blank=True, null=True)),
                ('broadcast', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=20)),
                ('cover', models.CharField(max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.ImageField(upload_to='static/img')),
                ('size', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('album_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='album.Album')),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
    ]
